import type { FileMap } from '~/lib/stores/files';

const GITHUB_API = 'https://api.github.com';

export async function createAppRepo(orgName: string, repoName: string, token: string): Promise<string> {
  const res = await fetch(`${GITHUB_API}/orgs/${orgName}/repos`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github+json',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      name: repoName,
      private: true,
      auto_init: true,
      description: 'Generated by Prompify',
    }),
  });

  if (!res.ok) {
    // Repo may already exist — check
    if (res.status === 422) {
      return getRepoUrl(orgName, repoName);
    }
    const err = await res.text();
    throw new Error(`Failed to create repo: ${res.status} ${err}`);
  }

  const data = (await res.json()) as { html_url: string };
  return data.html_url;
}

export function getRepoUrl(owner: string, repo: string): string {
  return `https://github.com/${owner}/${repo}`;
}

export async function getFileSha(
  owner: string,
  repo: string,
  path: string,
  token: string
): Promise<string | null> {
  const res = await fetch(`${GITHUB_API}/repos/${owner}/${repo}/contents/${path}`, {
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github+json',
    },
  });
  if (!res.ok) return null;
  const data = (await res.json()) as { sha?: string };
  return data.sha ?? null;
}

export async function pushGeneratedFiles(
  owner: string,
  repo: string,
  files: FileMap,
  token: string,
  commitMessage = `feat: AI-generated app v${Date.now()}`
): Promise<{ pushed: number; failed: string[] }> {
  const failed: string[] = [];
  let pushed = 0;

  for (const [rawPath, dirent] of Object.entries(files)) {
    if (!dirent || dirent.type === 'folder') continue;

    const content = dirent.content ?? '';
    const filePath = rawPath.startsWith('/') ? rawPath.slice(1) : rawPath;
    const encoded = Buffer.from(content, 'utf8').toString('base64');

    const sha = await getFileSha(owner, repo, filePath, token);

    const body: Record<string, unknown> = {
      message: commitMessage,
      content: encoded,
    };
    if (sha) body.sha = sha;

    const res = await fetch(`${GITHUB_API}/repos/${owner}/${repo}/contents/${filePath}`, {
      method: 'PUT',
      headers: {
        Authorization: `Bearer ${token}`,
        Accept: 'application/vnd.github+json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(body),
    });

    if (res.ok) {
      pushed++;
    } else {
      failed.push(filePath);
    }
  }

  return { pushed, failed };
}

export async function getOrgRepos(orgName: string, token: string): Promise<{ name: string; html_url: string; updated_at: string }[]> {
  const res = await fetch(`${GITHUB_API}/orgs/${orgName}/repos?type=private&sort=updated&per_page=50`, {
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github+json',
    },
  });
  if (!res.ok) return [];
  return res.json();
}
